apiVersion: apps/v1
kind: Deployment
metadata:
  name: romrental
  labels:
    app: romrental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: romrental
  template:
    metadata:
      labels:
        app: romrental
    spec:
      containers:
        - name: romrental
          image: safronacr.azurecr.io/roaming-romrental:latest
          ports:
            - containerPort: 8080
#          readinessProbe:
#            httpGet:
#              path: '/actuator/health'
#              port: 8080
#            initialDelaySeconds: 10
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 10
#          livenessProbe:
#            httpGet:
#              path: '/actuator/health'
#              port: 8080
#            initialDelaySeconds: 120
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 5